repos:
- url: git@gitlab.com:waewoo/prompt-unifier-data.git
  branch: null
  auth_config: null
  include_patterns: null
  exclude_patterns: null
last_sync_timestamp: '2025-11-26T20:36:49.742903+00:00'
repo_metadata:
- url: git@gitlab.com:waewoo/prompt-unifier-data.git
  branch: main
  commit: 3f044a8
  timestamp: '2025-11-26T20:36:49.715919+00:00'
storage_path: /root/.prompt-unifier/storage
deploy_tags: null
target_handlers: null
handlers: null
