repos:
- url: /root/travail/prompt-unifier-data
  branch: null
  auth_config: null
  include_patterns: null
  exclude_patterns: null
last_sync_timestamp: '2026-02-22T16:55:15.873222+00:00'
repo_metadata:
- url: /root/travail/prompt-unifier-data
  branch: main
  commit: 7628e83
  timestamp: '2026-02-22T16:55:15.802398+00:00'
storage_path: /root/.prompt-unifier/storage
deploy_tags: null
target_handlers: null
ai_provider: mistral/codestral-latest
handlers: null
