repos:
- url: git@gitlab.com:waewoo/prompt-unifier-data.git
  branch: null
  auth_config: null
  include_patterns: null
  exclude_patterns: null
last_sync_timestamp: '2025-11-27T18:19:37.633461+00:00'
repo_metadata:
- url: git@gitlab.com:waewoo/prompt-unifier-data.git
  branch: main
  commit: c54cf4e
  timestamp: '2025-11-27T18:19:37.587247+00:00'
storage_path: /root/.prompt-unifier/storage
deploy_tags: null
target_handlers: null
handlers: null
