repos:
- url: /root/travail/prompt-unifier-data
  branch: null
  auth_config: null
  include_patterns: null
  exclude_patterns: null
last_sync_timestamp: '2026-02-22T21:17:52.632735+00:00'
repo_metadata:
- url: /root/travail/prompt-unifier-data
  branch: main
  commit: 813e09f
  timestamp: '2026-02-22T21:17:52.565783+00:00'
storage_path: /root/.prompt-unifier/storage
deploy_tags: null
target_handlers: null
ai_provider: mistral/codestral-latest
handlers: null
