version: 2.1.1
last_compiled: 2025-11-08 16:48:46

# ================================================
# Compiled with the following settings:
#
# To change these settings, run ~/agent-os/scripts/project-update.sh to re-compile your project with the new settings.
# ================================================
profile: python
claude_code_commands: true
use_claude_code_subagents: true
agent_os_commands: true
standards_as_claude_code_skills: true
